name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install requests
        run: pip install requests

      - name: Run ping script
        run: python scripts/keep_alive.py